// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

#include "Entity.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PBEntityMailbox::PBEntityMailbox(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.entity_id_)*/uint64_t{0u}
  , /*decltype(_impl_.server_id_)*/0u} {}
struct PBEntityMailboxDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBEntityMailboxDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBEntityMailboxDefaultTypeInternal() {}
  union {
    PBEntityMailbox _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBEntityMailboxDefaultTypeInternal _PBEntityMailbox_default_instance_;
static ::_pb::Metadata file_level_metadata_Entity_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Entity_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Entity_2eproto = nullptr;

const uint32_t TableStruct_Entity_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::PBEntityMailbox, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::PBEntityMailbox, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PBEntityMailbox, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::PBEntityMailbox, _impl_.server_id_),
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::PBEntityMailbox)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PBEntityMailbox_default_instance_._instance,
};

const char descriptor_table_protodef_Entity_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Entity.proto\"7\n\017PBEntityMailbox\022\021\n\tent"
  "ity_id\030\001 \001(\004\022\021\n\tserver_id\030\002 \001(\r*\035\n\016enPBE"
  "ntityType\022\013\n\007ET_NONE\020\001"
  ;
static ::_pbi::once_flag descriptor_table_Entity_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Entity_2eproto = {
    false, false, 102, descriptor_table_protodef_Entity_2eproto,
    "Entity.proto",
    &descriptor_table_Entity_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_Entity_2eproto::offsets,
    file_level_metadata_Entity_2eproto, file_level_enum_descriptors_Entity_2eproto,
    file_level_service_descriptors_Entity_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Entity_2eproto_getter() {
  return &descriptor_table_Entity_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Entity_2eproto(&descriptor_table_Entity_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* enPBEntityType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Entity_2eproto);
  return file_level_enum_descriptors_Entity_2eproto[0];
}
bool enPBEntityType_IsValid(int value) {
  switch (value) {
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class PBEntityMailbox::_Internal {
 public:
  using HasBits = decltype(std::declval<PBEntityMailbox>()._impl_._has_bits_);
  static void set_has_entity_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_server_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

PBEntityMailbox::PBEntityMailbox(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PBEntityMailbox)
}
PBEntityMailbox::PBEntityMailbox(const PBEntityMailbox& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBEntityMailbox* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.entity_id_){}
    , decltype(_impl_.server_id_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.entity_id_, &from._impl_.entity_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.server_id_) -
    reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.server_id_));
  // @@protoc_insertion_point(copy_constructor:PBEntityMailbox)
}

inline void PBEntityMailbox::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.entity_id_){uint64_t{0u}}
    , decltype(_impl_.server_id_){0u}
  };
}

PBEntityMailbox::~PBEntityMailbox() {
  // @@protoc_insertion_point(destructor:PBEntityMailbox)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBEntityMailbox::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PBEntityMailbox::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBEntityMailbox::Clear() {
// @@protoc_insertion_point(message_clear_start:PBEntityMailbox)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.entity_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.server_id_) -
        reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.server_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBEntityMailbox::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint64 entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_entity_id(&has_bits);
          _impl_.entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 server_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_server_id(&has_bits);
          _impl_.server_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBEntityMailbox::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBEntityMailbox)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 entity_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_entity_id(), target);
  }

  // optional uint32 server_id = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_server_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBEntityMailbox)
  return target;
}

size_t PBEntityMailbox::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBEntityMailbox)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint64 entity_id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_entity_id());
    }

    // optional uint32 server_id = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_server_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBEntityMailbox::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBEntityMailbox::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBEntityMailbox::GetClassData() const { return &_class_data_; }


void PBEntityMailbox::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBEntityMailbox*>(&to_msg);
  auto& from = static_cast<const PBEntityMailbox&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBEntityMailbox)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.entity_id_ = from._impl_.entity_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.server_id_ = from._impl_.server_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBEntityMailbox::CopyFrom(const PBEntityMailbox& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBEntityMailbox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBEntityMailbox::IsInitialized() const {
  return true;
}

void PBEntityMailbox::InternalSwap(PBEntityMailbox* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBEntityMailbox, _impl_.server_id_)
      + sizeof(PBEntityMailbox::_impl_.server_id_)
      - PROTOBUF_FIELD_OFFSET(PBEntityMailbox, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PBEntityMailbox::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Entity_2eproto_getter, &descriptor_table_Entity_2eproto_once,
      file_level_metadata_Entity_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PBEntityMailbox*
Arena::CreateMaybeMessage< ::PBEntityMailbox >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PBEntityMailbox >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
