// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xCommond.proto

#include "xCommond.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xCommond_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xCommond_2eproto = nullptr;
const uint32_t TableStruct_xCommond_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xCommond_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016xCommond.proto*^\n\007CmdType\022\032\n\026PB_SYSTEM"
  "_INTERNAL_CMD\020\001\022\021\n\rPB_COMMON_CMD\020\002\022\017\n\013PB"
  "_WORK_CMD\020\003\022\023\n\016PB_COMMAND_MAX\020\377\001"
  ;
static ::_pbi::once_flag descriptor_table_xCommond_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xCommond_2eproto = {
    false, false, 112, descriptor_table_protodef_xCommond_2eproto,
    "xCommond.proto",
    &descriptor_table_xCommond_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_xCommond_2eproto::offsets,
    nullptr, file_level_enum_descriptors_xCommond_2eproto,
    file_level_service_descriptors_xCommond_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xCommond_2eproto_getter() {
  return &descriptor_table_xCommond_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xCommond_2eproto(&descriptor_table_xCommond_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CmdType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xCommond_2eproto);
  return file_level_enum_descriptors_xCommond_2eproto[0];
}
bool CmdType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 255:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
